#!/bin/sh
export PYTHONPATH=/home/ra/workspace/code/starter_toolboxes/codebase/build/lib/python2.7/dist-packages:/home/ra/workspace/code/starter_toolboxes/codebase/build/lib/python2.7/site-packages:${PYTHONPATH}
exec /usr/bin/python -m bot_log2mat.log_to_mat $*
