/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package agile;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class pose_t implements lcm.lcm.LCMEncodable
{
    public long timestampJetson;
    public double position[];
    public double orient[];
    public double variances[][];
 
    public pose_t()
    {
        position = new double[3];
        orient = new double[4];
        variances = new double[6][6];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x48b2dc9b1a511f1fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(agile.pose_t.class))
            return 0L;
 
        classes.add(agile.pose_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestampJetson); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.position[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeDouble(this.orient[a]); 
        }
 
        for (int a = 0; a < 6; a++) {
            for (int b = 0; b < 6; b++) {
                outs.writeDouble(this.variances[a][b]); 
            }
        }
 
    }
 
    public pose_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public pose_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static agile.pose_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        agile.pose_t o = new agile.pose_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestampJetson = ins.readLong();
 
        this.position = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.position[a] = ins.readDouble();
        }
 
        this.orient = new double[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.orient[a] = ins.readDouble();
        }
 
        this.variances = new double[(int) 6][(int) 6];
        for (int a = 0; a < 6; a++) {
            for (int b = 0; b < 6; b++) {
                this.variances[a][b] = ins.readDouble();
            }
        }
 
    }
 
    public agile.pose_t copy()
    {
        agile.pose_t outobj = new agile.pose_t();
        outobj.timestampJetson = this.timestampJetson;
 
        outobj.position = new double[(int) 3];
        System.arraycopy(this.position, 0, outobj.position, 0, 3); 
        outobj.orient = new double[(int) 4];
        System.arraycopy(this.orient, 0, outobj.orient, 0, 4); 
        outobj.variances = new double[(int) 6][(int) 6];
        for (int a = 0; a < 6; a++) {
            System.arraycopy(this.variances[a], 0, outobj.variances[a], 0, 6);        }
 
        return outobj;
    }
 
}

