/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package agile;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class powerAdjust_t implements lcm.lcm.LCMEncodable
{
    public long timestampJetson;
    public double powerGain;
    public double tBiasPDO;
    public double yBiasPDO;
    public double pBiasPDO;
    public double rBiasPDO;
    public double pyAdjustPDO;
    public double dyAdjustPDO;
    public double ppAdjustPDO;
    public double dpAdjustPDO;
    public double prAdjustPDO;
    public double drAdjustPDO;
    public double ptAdjustPDO;
    public double dtAdjustPDO;
 
    public powerAdjust_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x841bbf5ee272e80bL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(agile.powerAdjust_t.class))
            return 0L;
 
        classes.add(agile.powerAdjust_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestampJetson); 
 
        outs.writeDouble(this.powerGain); 
 
        outs.writeDouble(this.tBiasPDO); 
 
        outs.writeDouble(this.yBiasPDO); 
 
        outs.writeDouble(this.pBiasPDO); 
 
        outs.writeDouble(this.rBiasPDO); 
 
        outs.writeDouble(this.pyAdjustPDO); 
 
        outs.writeDouble(this.dyAdjustPDO); 
 
        outs.writeDouble(this.ppAdjustPDO); 
 
        outs.writeDouble(this.dpAdjustPDO); 
 
        outs.writeDouble(this.prAdjustPDO); 
 
        outs.writeDouble(this.drAdjustPDO); 
 
        outs.writeDouble(this.ptAdjustPDO); 
 
        outs.writeDouble(this.dtAdjustPDO); 
 
    }
 
    public powerAdjust_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public powerAdjust_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static agile.powerAdjust_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        agile.powerAdjust_t o = new agile.powerAdjust_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestampJetson = ins.readLong();
 
        this.powerGain = ins.readDouble();
 
        this.tBiasPDO = ins.readDouble();
 
        this.yBiasPDO = ins.readDouble();
 
        this.pBiasPDO = ins.readDouble();
 
        this.rBiasPDO = ins.readDouble();
 
        this.pyAdjustPDO = ins.readDouble();
 
        this.dyAdjustPDO = ins.readDouble();
 
        this.ppAdjustPDO = ins.readDouble();
 
        this.dpAdjustPDO = ins.readDouble();
 
        this.prAdjustPDO = ins.readDouble();
 
        this.drAdjustPDO = ins.readDouble();
 
        this.ptAdjustPDO = ins.readDouble();
 
        this.dtAdjustPDO = ins.readDouble();
 
    }
 
    public agile.powerAdjust_t copy()
    {
        agile.powerAdjust_t outobj = new agile.powerAdjust_t();
        outobj.timestampJetson = this.timestampJetson;
 
        outobj.powerGain = this.powerGain;
 
        outobj.tBiasPDO = this.tBiasPDO;
 
        outobj.yBiasPDO = this.yBiasPDO;
 
        outobj.pBiasPDO = this.pBiasPDO;
 
        outobj.rBiasPDO = this.rBiasPDO;
 
        outobj.pyAdjustPDO = this.pyAdjustPDO;
 
        outobj.dyAdjustPDO = this.dyAdjustPDO;
 
        outobj.ppAdjustPDO = this.ppAdjustPDO;
 
        outobj.dpAdjustPDO = this.dpAdjustPDO;
 
        outobj.prAdjustPDO = this.prAdjustPDO;
 
        outobj.drAdjustPDO = this.drAdjustPDO;
 
        outobj.ptAdjustPDO = this.ptAdjustPDO;
 
        outobj.dtAdjustPDO = this.dtAdjustPDO;
 
        return outobj;
    }
 
}

