/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package agile;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class stateVariances_t implements lcm.lcm.LCMEncodable
{
    public long timestampJetson;
    public double position[];
    public double orient[];
    public double veloPositionBody[];
    public double veloOrientBody[];
    public double imuBiasAccel[];
    public double imuBiasGyro[];
    public double imuVarianceAccel[];
    public double imuVarianceGyro[];
    public double variances[][];
 
    public stateVariances_t()
    {
        position = new double[3];
        orient = new double[4];
        veloPositionBody = new double[3];
        veloOrientBody = new double[3];
        imuBiasAccel = new double[3];
        imuBiasGyro = new double[3];
        imuVarianceAccel = new double[3];
        imuVarianceGyro = new double[3];
        variances = new double[12][12];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xa2003c3f59a5badeL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(agile.stateVariances_t.class))
            return 0L;
 
        classes.add(agile.stateVariances_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestampJetson); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.position[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeDouble(this.orient[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.veloPositionBody[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.veloOrientBody[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.imuBiasAccel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.imuBiasGyro[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.imuVarianceAccel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.imuVarianceGyro[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            for (int b = 0; b < 12; b++) {
                outs.writeDouble(this.variances[a][b]); 
            }
        }
 
    }
 
    public stateVariances_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public stateVariances_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static agile.stateVariances_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        agile.stateVariances_t o = new agile.stateVariances_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestampJetson = ins.readLong();
 
        this.position = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.position[a] = ins.readDouble();
        }
 
        this.orient = new double[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.orient[a] = ins.readDouble();
        }
 
        this.veloPositionBody = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.veloPositionBody[a] = ins.readDouble();
        }
 
        this.veloOrientBody = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.veloOrientBody[a] = ins.readDouble();
        }
 
        this.imuBiasAccel = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.imuBiasAccel[a] = ins.readDouble();
        }
 
        this.imuBiasGyro = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.imuBiasGyro[a] = ins.readDouble();
        }
 
        this.imuVarianceAccel = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.imuVarianceAccel[a] = ins.readDouble();
        }
 
        this.imuVarianceGyro = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.imuVarianceGyro[a] = ins.readDouble();
        }
 
        this.variances = new double[(int) 12][(int) 12];
        for (int a = 0; a < 12; a++) {
            for (int b = 0; b < 12; b++) {
                this.variances[a][b] = ins.readDouble();
            }
        }
 
    }
 
    public agile.stateVariances_t copy()
    {
        agile.stateVariances_t outobj = new agile.stateVariances_t();
        outobj.timestampJetson = this.timestampJetson;
 
        outobj.position = new double[(int) 3];
        System.arraycopy(this.position, 0, outobj.position, 0, 3); 
        outobj.orient = new double[(int) 4];
        System.arraycopy(this.orient, 0, outobj.orient, 0, 4); 
        outobj.veloPositionBody = new double[(int) 3];
        System.arraycopy(this.veloPositionBody, 0, outobj.veloPositionBody, 0, 3); 
        outobj.veloOrientBody = new double[(int) 3];
        System.arraycopy(this.veloOrientBody, 0, outobj.veloOrientBody, 0, 3); 
        outobj.imuBiasAccel = new double[(int) 3];
        System.arraycopy(this.imuBiasAccel, 0, outobj.imuBiasAccel, 0, 3); 
        outobj.imuBiasGyro = new double[(int) 3];
        System.arraycopy(this.imuBiasGyro, 0, outobj.imuBiasGyro, 0, 3); 
        outobj.imuVarianceAccel = new double[(int) 3];
        System.arraycopy(this.imuVarianceAccel, 0, outobj.imuVarianceAccel, 0, 3); 
        outobj.imuVarianceGyro = new double[(int) 3];
        System.arraycopy(this.imuVarianceGyro, 0, outobj.imuVarianceGyro, 0, 3); 
        outobj.variances = new double[(int) 12][(int) 12];
        for (int a = 0; a < 12; a++) {
            System.arraycopy(this.variances[a], 0, outobj.variances[a], 0, 12);        }
 
        return outobj;
    }
 
}

