/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package agile;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class state_t implements lcm.lcm.LCMEncodable
{
    public long timestampJetson;
    public double position[];
    public double orient[];
    public double veloPositionBody[];
    public double veloOrientBody[];
    public double imuBiasaccel[];
    public double imuBiasgyro[];
 
    public state_t()
    {
        position = new double[3];
        orient = new double[4];
        veloPositionBody = new double[3];
        veloOrientBody = new double[3];
        imuBiasaccel = new double[3];
        imuBiasgyro = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xc128a8dd5f31f000L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(agile.state_t.class))
            return 0L;
 
        classes.add(agile.state_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestampJetson); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.position[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeDouble(this.orient[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.veloPositionBody[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.veloOrientBody[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.imuBiasaccel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.imuBiasgyro[a]); 
        }
 
    }
 
    public state_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public state_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static agile.state_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        agile.state_t o = new agile.state_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestampJetson = ins.readLong();
 
        this.position = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.position[a] = ins.readDouble();
        }
 
        this.orient = new double[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.orient[a] = ins.readDouble();
        }
 
        this.veloPositionBody = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.veloPositionBody[a] = ins.readDouble();
        }
 
        this.veloOrientBody = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.veloOrientBody[a] = ins.readDouble();
        }
 
        this.imuBiasaccel = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.imuBiasaccel[a] = ins.readDouble();
        }
 
        this.imuBiasgyro = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.imuBiasgyro[a] = ins.readDouble();
        }
 
    }
 
    public agile.state_t copy()
    {
        agile.state_t outobj = new agile.state_t();
        outobj.timestampJetson = this.timestampJetson;
 
        outobj.position = new double[(int) 3];
        System.arraycopy(this.position, 0, outobj.position, 0, 3); 
        outobj.orient = new double[(int) 4];
        System.arraycopy(this.orient, 0, outobj.orient, 0, 4); 
        outobj.veloPositionBody = new double[(int) 3];
        System.arraycopy(this.veloPositionBody, 0, outobj.veloPositionBody, 0, 3); 
        outobj.veloOrientBody = new double[(int) 3];
        System.arraycopy(this.veloOrientBody, 0, outobj.veloOrientBody, 0, 3); 
        outobj.imuBiasaccel = new double[(int) 3];
        System.arraycopy(this.imuBiasaccel, 0, outobj.imuBiasaccel, 0, 3); 
        outobj.imuBiasgyro = new double[(int) 3];
        System.arraycopy(this.imuBiasgyro, 0, outobj.imuBiasgyro, 0, 3); 
        return outobj;
    }
 
}

