// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "lcmtypes/agile_motorsPwms_t.h"

static int __agile_motorsPwms_t_hash_computed;
static int64_t __agile_motorsPwms_t_hash;

int64_t __agile_motorsPwms_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __agile_motorsPwms_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__agile_motorsPwms_t_get_hash;
    (void) cp;

    int64_t hash = (int64_t)0x0c4d9d8ad874e3a9LL
         + __int64_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __agile_motorsPwms_t_get_hash(void)
{
    if (!__agile_motorsPwms_t_hash_computed) {
        __agile_motorsPwms_t_hash = __agile_motorsPwms_t_hash_recursive(NULL);
        __agile_motorsPwms_t_hash_computed = 1;
    }

    return __agile_motorsPwms_t_hash;
}

int __agile_motorsPwms_t_encode_array(void *buf, int offset, int maxlen, const agile_motorsPwms_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestampJetson), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].pwms, 4);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int agile_motorsPwms_t_encode(void *buf, int offset, int maxlen, const agile_motorsPwms_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __agile_motorsPwms_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __agile_motorsPwms_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __agile_motorsPwms_t_encoded_array_size(const agile_motorsPwms_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].timestampJetson), 1);

        size += __int16_t_encoded_array_size(p[element].pwms, 4);

    }
    return size;
}

int agile_motorsPwms_t_encoded_size(const agile_motorsPwms_t *p)
{
    return 8 + __agile_motorsPwms_t_encoded_array_size(p, 1);
}

int __agile_motorsPwms_t_decode_array(const void *buf, int offset, int maxlen, agile_motorsPwms_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestampJetson), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].pwms, 4);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __agile_motorsPwms_t_decode_array_cleanup(agile_motorsPwms_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].timestampJetson), 1);

        __int16_t_decode_array_cleanup(p[element].pwms, 4);

    }
    return 0;
}

int agile_motorsPwms_t_decode(const void *buf, int offset, int maxlen, agile_motorsPwms_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __agile_motorsPwms_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __agile_motorsPwms_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int agile_motorsPwms_t_decode_cleanup(agile_motorsPwms_t *p)
{
    return __agile_motorsPwms_t_decode_array_cleanup(p, 1);
}

int __agile_motorsPwms_t_clone_array(const agile_motorsPwms_t *p, agile_motorsPwms_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].timestampJetson), &(q[element].timestampJetson), 1);

        __int16_t_clone_array(p[element].pwms, q[element].pwms, 4);

    }
    return 0;
}

agile_motorsPwms_t *agile_motorsPwms_t_copy(const agile_motorsPwms_t *p)
{
    agile_motorsPwms_t *q = (agile_motorsPwms_t*) malloc(sizeof(agile_motorsPwms_t));
    __agile_motorsPwms_t_clone_array(p, q, 1);
    return q;
}

void agile_motorsPwms_t_destroy(agile_motorsPwms_t *p)
{
    __agile_motorsPwms_t_decode_array_cleanup(p, 1);
    free(p);
}

int agile_motorsPwms_t_publish(lcm_t *lc, const char *channel, const agile_motorsPwms_t *p)
{
      int max_data_size = agile_motorsPwms_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = agile_motorsPwms_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _agile_motorsPwms_t_subscription_t {
    agile_motorsPwms_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void agile_motorsPwms_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    agile_motorsPwms_t p;
    memset(&p, 0, sizeof(agile_motorsPwms_t));
    status = agile_motorsPwms_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding agile_motorsPwms_t!!!\n", status);
        return;
    }

    agile_motorsPwms_t_subscription_t *h = (agile_motorsPwms_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    agile_motorsPwms_t_decode_cleanup (&p);
}

agile_motorsPwms_t_subscription_t* agile_motorsPwms_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    agile_motorsPwms_t_handler_t f, void *userdata)
{
    agile_motorsPwms_t_subscription_t *n = (agile_motorsPwms_t_subscription_t*)
                       malloc(sizeof(agile_motorsPwms_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 agile_motorsPwms_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg agile_motorsPwms_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int agile_motorsPwms_t_subscription_set_queue_capacity (agile_motorsPwms_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int agile_motorsPwms_t_unsubscribe(lcm_t *lcm, agile_motorsPwms_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe agile_motorsPwms_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

