"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class controlMode_t(object):
    __slots__ = ["timestampJetson", "controlMode"]

    def __init__(self):
        self.timestampJetson = 0
        self.controlMode = 0

    def encode(self):
        buf = BytesIO()
        buf.write(controlMode_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qh", self.timestampJetson, self.controlMode))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != controlMode_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return controlMode_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = controlMode_t()
        self.timestampJetson, self.controlMode = struct.unpack(">qh", buf.read(10))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if controlMode_t in parents: return 0
        tmphash = (0x6a126d11618741c9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if controlMode_t._packed_fingerprint is None:
            controlMode_t._packed_fingerprint = struct.pack(">Q", controlMode_t._get_hash_recursive([]))
        return controlMode_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

