"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class imuRaw_t(object):
    __slots__ = ["timestampArduino", "timestampJetson", "accel", "gyro", "magn", "baro"]

    def __init__(self):
        self.timestampArduino = 0
        self.timestampJetson = 0
        self.accel = [ 0.0 for dim0 in range(3) ]
        self.gyro = [ 0.0 for dim0 in range(3) ]
        self.magn = [ 0.0 for dim0 in range(3) ]
        self.baro = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(imuRaw_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qq", self.timestampArduino, self.timestampJetson))
        buf.write(struct.pack('>3d', *self.accel[:3]))
        buf.write(struct.pack('>3d', *self.gyro[:3]))
        buf.write(struct.pack('>3d', *self.magn[:3]))
        buf.write(struct.pack(">d", self.baro))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != imuRaw_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return imuRaw_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = imuRaw_t()
        self.timestampArduino, self.timestampJetson = struct.unpack(">qq", buf.read(16))
        self.accel = struct.unpack('>3d', buf.read(24))
        self.gyro = struct.unpack('>3d', buf.read(24))
        self.magn = struct.unpack('>3d', buf.read(24))
        self.baro = struct.unpack(">d", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if imuRaw_t in parents: return 0
        tmphash = (0x9e57e09861b1c526) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if imuRaw_t._packed_fingerprint is None:
            imuRaw_t._packed_fingerprint = struct.pack(">Q", imuRaw_t._get_hash_recursive([]))
        return imuRaw_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

