"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class statusDrone_t(object):
    __slots__ = ["timestampJetson", "status"]

    def __init__(self):
        self.timestampJetson = 0
        self.status = 0

    def encode(self):
        buf = BytesIO()
        buf.write(statusDrone_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qh", self.timestampJetson, self.status))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != statusDrone_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return statusDrone_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = statusDrone_t()
        self.timestampJetson, self.status = struct.unpack(">qh", buf.read(10))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if statusDrone_t in parents: return 0
        tmphash = (0xca2a7aa8b75afce9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if statusDrone_t._packed_fingerprint is None:
            statusDrone_t._packed_fingerprint = struct.pack(">Q", statusDrone_t._get_hash_recursive([]))
        return statusDrone_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

