"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class statusPod_t(object):
    __slots__ = ["timestampJetson", "podName", "status"]

    def __init__(self):
        self.timestampJetson = 0
        self.podName = ""
        self.status = 0

    def encode(self):
        buf = BytesIO()
        buf.write(statusPod_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestampJetson))
        __podName_encoded = self.podName.encode('utf-8')
        buf.write(struct.pack('>I', len(__podName_encoded)+1))
        buf.write(__podName_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">h", self.status))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != statusPod_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return statusPod_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = statusPod_t()
        self.timestampJetson = struct.unpack(">q", buf.read(8))[0]
        __podName_len = struct.unpack('>I', buf.read(4))[0]
        self.podName = buf.read(__podName_len)[:-1].decode('utf-8', 'replace')
        self.status = struct.unpack(">h", buf.read(2))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if statusPod_t in parents: return 0
        tmphash = (0xce2c6cf37344e5a9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if statusPod_t._packed_fingerprint is None:
            statusPod_t._packed_fingerprint = struct.pack(">Q", statusPod_t._get_hash_recursive([]))
        return statusPod_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

